-- MySQL Script generated by MySQL Workbench
-- Mon Dec 11 15:06:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tequiladb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `usr_id` INT UNSIGNED NOT NULL,
  `usr_username` VARCHAR(45) NOT NULL,
  `usr_firstname` VARCHAR(45) NULL,
  `usr_lastname` VARCHAR(45) NULL,
  `usr_email` VARCHAR(255) NOT NULL,
  `usr_password` VARCHAR(45) NOT NULL,
  `usr_newsletter` TINYINT NULL DEFAULT 0,
  `usr_report` TINYINT NULL DEFAULT 0,
  UNIQUE INDEX `id_UNIQUE` (`usr_id` ASC),
  PRIMARY KEY (`usr_id`));


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `cat_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cat_name` VARCHAR(255) NULL,
  PRIMARY KEY (`cat_id`),
  UNIQUE INDEX `id_UNIQUE` (`cat_id` ASC));


-- -----------------------------------------------------
-- Table `country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `country` ;

CREATE TABLE IF NOT EXISTS `country` (
  `cou_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cou_name` VARCHAR(255) NULL,
  PRIMARY KEY (`cou_id`),
  UNIQUE INDEX `id_UNIQUE` (`cou_id` ASC));


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `customer` ;

CREATE TABLE IF NOT EXISTS `customer` (
  `cust_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cust_firstname` VARCHAR(45) NULL,
  `cust_lastname` VARCHAR(45) NULL,
  `cust_email` VARCHAR(45) NULL,
  `cust_address` VARCHAR(45) NULL,
  `cust_postcode` VARCHAR(10) NULL,
  `cust_city` VARCHAR(45) NULL,
  `cust_cou_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cust_id`, `cust_cou_id`),
  UNIQUE INDEX `id_UNIQUE` (`cust_id` ASC),
  INDEX `fk_customer_country_idx` (`cust_cou_id` ASC),
  CONSTRAINT `fk_customer_country`
    FOREIGN KEY (`cust_cou_id`)
    REFERENCES `country` (`cou_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order` ;

CREATE TABLE IF NOT EXISTS `order` (
  `ord_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ord_date` DATE NULL,
  `ord_payment` VARCHAR(15) NULL,
  `ord_cust_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ord_id`, `ord_cust_id`),
  UNIQUE INDEX `id_UNIQUE` (`ord_id` ASC),
  INDEX `fk_order_customer1_idx` (`ord_cust_id` ASC),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`ord_cust_id`)
    REFERENCES `customer` (`cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `prod_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `prod_name` VARCHAR(45) NULL,
  `prod_description` VARCHAR(255) NULL,
  `prod_price` FLOAT UNSIGNED NULL,
  `prod_stock` INT UNSIGNED NULL,
  `prod_vat` INT NULL,
  `prod_cat_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`prod_id`, `prod_cat_id`),
  INDEX `fk_product_category1_idx` (`prod_cat_id` ASC),
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`prod_cat_id`)
    REFERENCES `category` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `orderline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orderline` ;

CREATE TABLE IF NOT EXISTS `orderline` (
  `ol_ord_id` INT UNSIGNED NOT NULL,
  `ol_prod_id` INT UNSIGNED NOT NULL,
  `ol_quantity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ol_ord_id`, `ol_prod_id`),
  INDEX `fk_order_has_product_product1_idx` (`ol_prod_id` ASC),
  INDEX `fk_order_has_product_order1_idx` (`ol_ord_id` ASC),
  CONSTRAINT `fk_order_has_product_order1`
    FOREIGN KEY (`ol_ord_id`)
    REFERENCES `order` (`ord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_product_product1`
    FOREIGN KEY (`ol_prod_id`)
    REFERENCES `product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
